### ISSUE TITLE
&nbsp;没有解析掉

### ISSUE THREAD

**Issue by wuhuajie** [skyFi/html2wxml#1]
如果html里面包含&nbsp;，  则&nbsp; 会最终显示在小程序里面

**Comment by skyFi** [comment]
已增加支持常用html转译，谢谢你的反馈 :) [commit](https://github.com/skyFi/html2wxml/commit/5fa6a8f22778a6031910f808b0c86f9de1b057a0)

**Comment by wuhuajie** [comment]
还是有问题.  我自己局部fix了一下. 你看看
    chars: function (text) {
      debug(text);
      if(text == ' ') {
        return;
      }
      text=text.replace(/&nbsp;/ig, ' '); 
      var index = 0;
            console.log(text);

      while(text.charAt(index) == ' ') {
          index = index + 1;
      }

      text.indexOf('&nbsp;')
      var node = {
        node: 'text',
        text: text,
      };
      if(index > 0) {
          node.attr = node.attr || {};
          node.attr.style = 'margin-left: ' + 16 * index + 'rpx;';
      }

**Comment by skyFi** [comment]
嗯，直接替换掉就可以了
