### ISSUE TITLE
无法显示图片

### ISSUE THREAD

**Issue by eiffelluo** [skyFi/html2wxml#2]
用该工具转化微信公众号的文章后，无法显示图片。请问该工具支持图片的转换和适配吗？

**Comment by wuhuajie** [comment]
貌似不支持

**Comment by wylb** [comment]
在每个类似<block wx:if="{{tag.node == 'element'}}">后，添加<image wx:if="{{tag.tag == 'img'}}" class="{{tag.attr.class}}" style="{{tag.attr.style}}" src="{{tag.attr.src}}"></image>，并把之后的text改为view就可以显示图片

**Comment by skyFi** [comment]
@wylb 的意见值得考虑下，应该可以解决这个问题，希望解决后pull requests, thx
